language: python
cache: pip
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
env:
  - PY_ENV=development
services:
  - postgresql
  - redis-server
  - docker
install:
  - pip install -r requirements.txt
script:
  - flake8
  - python manage.py test
  - docker build -t pyslackers/website:$TRAVIS_BRANCH .
matrix:
  allow_failures:
    python: "3.7-dev"
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push pyslackers/website:$TRAVIS_BRANCH

